[package]
name = "galaxdb-server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "GalaxDB standalone server (PostgreSQL wire protocol)"

[lib]
name = "galaxdb_server"
path = "src/lib.rs"

[[bin]]
name = "galaxdb-server"
path = "src/main.rs"

[dependencies]
galaxdb-common.workspace = true
galaxdb-auth = { path = "../galaxdb-auth" }
galaxdb-sql = { path = "../galaxdb-sql" }
galaxdb-embedded.workspace = true
galaxdb-observe.workspace = true
galaxdb-wire.workspace = true
tokio = { workspace = true, features = ["full", "signal"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
tokio-postgres = "0.7"
tokio-postgres-rustls = "0.13"
rustls.workspace = true
rcgen = "0.13"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
serde_json.workspace = true
futures-util = "0.3"
bytes = "1"
