[package]
name = "galaxdb-sql"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "SQL Parser (sqlparser-rs + AuroraSQL), Query Planner, Query Executor"

[dependencies]
galaxdb-common.workspace = true
galaxdb-storage = { path = "../galaxdb-storage" }
galaxdb-versioning.workspace = true
galaxdb-vector = { path = "../galaxdb-vector" }
galaxdb-sidecar = { path = "../galaxdb-sidecar" }
galaxdb-auth = { path = "../galaxdb-auth" }
sqlparser.workspace = true
xxhash-rust.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio.workspace = true
tracing-subscriber = { workspace = true, features = ["registry"] }
