# GENERATED FILE — do not edit by hand.
# Regenerated by scripts/gen-homebrew-formula.sh during the release workflow
# from the SHA256 checksums of the published binaries.
class Galaxdb < Formula
  desc "AI-native database — SQL + vector search + training exports in one system"
  homepage "https://github.com/zentrix-innovative-labs/galaxdb"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/zentrix-innovative-labs/galaxdb/releases/download/v0.3.0/galaxdb-server-macos-x86_64"
      sha256 "8c004a955a69504e21564c0fb4c4d97e0059da657c567cbfc28658f382aec0df"
    end

    on_arm do
      url "https://github.com/zentrix-innovative-labs/galaxdb/releases/download/v0.3.0/galaxdb-server-macos-arm64"
      sha256 "8b67d0cc3fa8dd6c9b6cb56ad8a96553c59b7f4395dc9234be46e78e533accf2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zentrix-innovative-labs/galaxdb/releases/download/v0.3.0/galaxdb-server-linux-x86_64"
      sha256 "0e809096f1d5542a406c5dfa6a8b5a6075b83071f7e2f5f45b8beb99e1569077"
    end

    on_arm do
      url "https://github.com/zentrix-innovative-labs/galaxdb/releases/download/v0.3.0/galaxdb-server-linux-aarch64"
      sha256 "868b70c99b3daec7596a722794dc455050ab21c01b5896e01dc8034ba4e963b2"
    end
  end

  def install
    binary_name = stable.url.split("/").last
    bin.install binary_name => "galaxdb-server"
  end

  def caveats
    <<~EOS
      To start GalaxDB:
        galaxdb-server --data-dir ~/galaxdb-data --port 5433 --auth

      Python client:
        pip install galaxdb-client

      For embedding support, also download the sidecar from the same release
      and start with:
        galaxdb-server --data-dir ~/galaxdb-data --sidecar galaxdb-sidecar \\
                       --model sentence-transformers/all-MiniLM-L6-v2

      Docs: https://github.com/zentrix-innovative-labs/galaxdb
    EOS
  end

  test do
    system "#{bin}/galaxdb-server", "--help"
  end
end
