# GENERATED FILE — do not edit by hand.
# Regenerated by scripts/gen-homebrew-formula.sh during the release workflow
# from the SHA256 checksums of the published binaries.
class Galaxdb < Formula
  desc "AI-native database — SQL + vector search + training exports in one system"
  homepage "https://github.com/zentrix-innovative-labs/galaxdb"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/zentrix-innovative-labs/galaxdb/releases/download/v0.7.0/galaxdb-server-macos-x86_64"
      sha256 "9a9a168098e65837a90eaeb7282123be74a8f1d53326ea9ed0f7eb1a41aaba3e"
    end

    on_arm do
      url "https://github.com/zentrix-innovative-labs/galaxdb/releases/download/v0.7.0/galaxdb-server-macos-arm64"
      sha256 "1781d994ededa7bbc81a396159ee067551537af2d9f56a9de678bd5729c73904"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zentrix-innovative-labs/galaxdb/releases/download/v0.7.0/galaxdb-server-linux-x86_64"
      sha256 "f357a6f16cf933db5526337560d7f0bc1c167804afe80335f1bbdfcf2e1fd4fd"
    end

    on_arm do
      url "https://github.com/zentrix-innovative-labs/galaxdb/releases/download/v0.7.0/galaxdb-server-linux-aarch64"
      sha256 "cbf3cf5921f001af8ad96c5541fd9d3cec5b56c16dcf1487fa91b4f6add1e66f"
    end
  end

  def install
    binary_name = stable.url.split("/").last
    bin.install binary_name => "galaxdb-server"
  end

  def caveats
    <<~EOS
      To start GalaxDB:
        galaxdb-server --data-dir ~/galaxdb-data --port 5433 --auth

      Python client:
        pip install galaxdb-client

      For embedding support, also download the sidecar from the same release
      and start with:
        galaxdb-server --data-dir ~/galaxdb-data --sidecar galaxdb-sidecar \\
                       --model sentence-transformers/all-MiniLM-L6-v2

      Docs: https://github.com/zentrix-innovative-labs/galaxdb
    EOS
  end

  test do
    system "#{bin}/galaxdb-server", "--help"
  end
end
