# GENERATED FILE — do not edit by hand.
# Regenerated by scripts/gen-homebrew-formula.sh during the release workflow
# from the SHA256 checksums of the published binaries.
class Galaxdb < Formula
  desc "AI-native database — SQL + vector search + training exports in one system"
  homepage "https://github.com/zentrix-innovative-labs/galaxdb"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/zentrix-innovative-labs/galaxdb/releases/download/v0.6.0/galaxdb-server-macos-x86_64"
      sha256 "cc30ce5c514046a2f285219406d9cea0fca386a0e66323efca667daa4599b368"
    end

    on_arm do
      url "https://github.com/zentrix-innovative-labs/galaxdb/releases/download/v0.6.0/galaxdb-server-macos-arm64"
      sha256 "11cde1ca5b9e304f4d7beae79eda306e64a73181993e9211f6524bbdb4fc31db"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zentrix-innovative-labs/galaxdb/releases/download/v0.6.0/galaxdb-server-linux-x86_64"
      sha256 "bd732f1f0f532eefbc588a79340250dcbbe9762617a72abc42a94b9bbfdf675e"
    end

    on_arm do
      url "https://github.com/zentrix-innovative-labs/galaxdb/releases/download/v0.6.0/galaxdb-server-linux-aarch64"
      sha256 "7a09da3e08b166e565820037059301791c376df8b2f859bd4dd4d83249264ba2"
    end
  end

  def install
    binary_name = stable.url.split("/").last
    bin.install binary_name => "galaxdb-server"
  end

  def caveats
    <<~EOS
      To start GalaxDB:
        galaxdb-server --data-dir ~/galaxdb-data --port 5433 --auth

      Python client:
        pip install galaxdb-client

      For embedding support, also download the sidecar from the same release
      and start with:
        galaxdb-server --data-dir ~/galaxdb-data --sidecar galaxdb-sidecar \\
                       --model sentence-transformers/all-MiniLM-L6-v2

      Docs: https://github.com/zentrix-innovative-labs/galaxdb
    EOS
  end

  test do
    system "#{bin}/galaxdb-server", "--help"
  end
end
