#!/usr/bin/env bash
# Regenerate Formula/galaxdb.rb from the real release artifacts.
#
# The Homebrew formula must pin a version and a SHA256 for every platform
# binary (Homebrew refuses URL downloads without a checksum). Hand-editing
# five values on every release is error-prone, so this script derives all of
# them from the `.sha256` files that `release.yml` computes for each built
# binary — no value is typed by a human.
#
# Usage:
#   scripts/gen-homebrew-formula.sh <version> <checksum-dir> [output-file]
#
#   <version>       release version WITHOUT the leading "v" (e.g. 0.3.0)
#   <checksum-dir>  directory containing galaxdb-server-<platform>.sha256 files
#                   (each holds a "<hash>  <filename>" line, as produced by
#                   `sha256sum`)
#   [output-file]   defaults to Formula/galaxdb.rb relative to repo root
#
# Exits non-zero if any required checksum is missing — never emits a formula
# with a blank or stale hash.

set -euo pipefail

if [ "$#" -lt 2 ]; then
  echo "usage: $0 <version> <checksum-dir> [output-file]" >&2
  exit 2
fi

VERSION="${1#v}"          # strip a leading v if the caller passed one
DIST="$2"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${3:-$REPO_ROOT/Formula/galaxdb.rb}"
REPO="zentrix-innovative-labs/galaxdb"

sha_for() {
  local platform="$1"
  local f="$DIST/galaxdb-server-${platform}.sha256"
  if [ ! -f "$f" ]; then
    echo "ERROR: missing checksum file: $f" >&2
    exit 1
  fi
  # A sha256sum line is "<64-hex>  <filename>"; take the first field.
  local hash
  hash="$(awk 'NR==1{print $1}' "$f")"
  if [ "${#hash}" -ne 64 ]; then
    echo "ERROR: malformed sha256 in $f: '$hash'" >&2
    exit 1
  fi
  printf '%s' "$hash"
}

SHA_MAC_X86="$(sha_for macos-x86_64)"
SHA_MAC_ARM="$(sha_for macos-arm64)"
SHA_LIN_X86="$(sha_for linux-x86_64)"
SHA_LIN_ARM="$(sha_for linux-aarch64)"

# Write the formula from a no-expansion heredoc using placeholder tokens,
# then substitute the real values. This keeps Ruby's own backslashes and
# `#{...}` interpolation intact without shell-escaping gymnastics.
cat > "$OUT" <<'RUBY'
# GENERATED FILE — do not edit by hand.
# Regenerated by scripts/gen-homebrew-formula.sh during the release workflow
# from the SHA256 checksums of the published binaries.
class Galaxdb < Formula
  desc "AI-native database — SQL + vector search + training exports in one system"
  homepage "https://github.com/zentrix-innovative-labs/galaxdb"
  version "__VERSION__"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/zentrix-innovative-labs/galaxdb/releases/download/v__VERSION__/galaxdb-server-macos-x86_64"
      sha256 "__SHA_MAC_X86__"
    end

    on_arm do
      url "https://github.com/zentrix-innovative-labs/galaxdb/releases/download/v__VERSION__/galaxdb-server-macos-arm64"
      sha256 "__SHA_MAC_ARM__"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zentrix-innovative-labs/galaxdb/releases/download/v__VERSION__/galaxdb-server-linux-x86_64"
      sha256 "__SHA_LIN_X86__"
    end

    on_arm do
      url "https://github.com/zentrix-innovative-labs/galaxdb/releases/download/v__VERSION__/galaxdb-server-linux-aarch64"
      sha256 "__SHA_LIN_ARM__"
    end
  end

  def install
    binary_name = stable.url.split("/").last
    bin.install binary_name => "galaxdb-server"
  end

  def caveats
    <<~EOS
      To start GalaxDB:
        galaxdb-server --data-dir ~/galaxdb-data --port 5433 --auth

      Python client:
        pip install galaxdb-client

      For embedding support, also download the sidecar from the same release
      and start with:
        galaxdb-server --data-dir ~/galaxdb-data --sidecar galaxdb-sidecar \\
                       --model sentence-transformers/all-MiniLM-L6-v2

      Docs: https://github.com/zentrix-innovative-labs/galaxdb
    EOS
  end

  test do
    system "#{bin}/galaxdb-server", "--help"
  end
end
RUBY

# Substitute the derived values. Use a temp file for portable in-place edit
# (GNU vs BSD sed differ on -i).
tmp="$(mktemp)"
sed \
  -e "s|__VERSION__|${VERSION}|g" \
  -e "s|__SHA_MAC_X86__|${SHA_MAC_X86}|g" \
  -e "s|__SHA_MAC_ARM__|${SHA_MAC_ARM}|g" \
  -e "s|__SHA_LIN_X86__|${SHA_LIN_X86}|g" \
  -e "s|__SHA_LIN_ARM__|${SHA_LIN_ARM}|g" \
  "$OUT" > "$tmp"
mv "$tmp" "$OUT"

echo "Regenerated $OUT for v${VERSION}"
echo "  macos-x86_64  ${SHA_MAC_X86}"
echo "  macos-arm64   ${SHA_MAC_ARM}"
echo "  linux-x86_64  ${SHA_LIN_X86}"
echo "  linux-aarch64 ${SHA_LIN_ARM}"
