[package]
name = "galaxdb-embedded"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Embedded library API (Python FFI via PyO3)"

[lib]
name = "galaxdb_embedded"
crate-type = ["lib"]

[dependencies]
galaxdb-common.workspace = true
